#!/bin/bash
# SkillBridge - Complete Setup Guide
# This script helps you set up Supabase database automatically

echo "🚀 SkillBridge Full Setup Guide"
echo "================================"
echo ""
echo "This guide will walk you through setting up your fully functional prototype."
echo ""

echo "📋 STEP 1: Create Supabase Project"
echo "-----------------------------------"
echo "1. Go to https://supabase.com"
echo "2. Click 'Sign Up' or 'Sign In'"
echo "3. Create a new organization (or use existing)"
echo "4. Click 'New Project'"
echo "5. Fill in:"
echo "   - Project name: SkillBridge"
echo "   - Database password: (save this!)"
echo "   - Region: (choose closest to you)"
echo "6. Click 'Create new project' (wait 2-3 minutes)"
echo ""

echo "📝 STEP 2: Get API Keys"
echo "----------------------"
echo "1. In Supabase Dashboard, go to Settings > API"
echo "2. Copy these values:"
echo "   - Project URL (starts with https://...supabase.co)"
echo "   - Anon Public Key (starts with eyJ...)"
echo ""

echo "🔧 STEP 3: Create .env.local File"
echo "----------------------------------"
echo "Create a file at the root: .env.local"
echo ""
echo "Paste this (replace with your actual keys):"
echo ""
echo "VITE_SUPABASE_URL=https://your-project.supabase.co"
echo "VITE_SUPABASE_ANON_KEY=eyJ0eXAiOiJKV1QiLCJhbGc..."
echo ""

echo "🗄️  STEP 4: Run Database Setup"
echo "------------------------------"
echo "1. In Supabase Dashboard, go to 'SQL Editor'"
echo "2. Click 'New Query'"
echo "3. Copy contents of: supabase/migrations/001_initial_schema.sql"
echo "4. Paste into the SQL editor"
echo "5. Click 'Run' (wait for success)"
echo ""

echo "📦 STEP 5: Install Dependencies"
echo "-------------------------------"
echo "Run:"
echo "npm install"
echo ""

echo "🚀 STEP 6: Start Development Server"
echo "-----------------------------------"
echo "Run:"
echo "npm run dev"
echo ""

echo "✅ STEP 7: Test Authentication"
echo "------------------------------"
echo "1. Open http://localhost:5173"
echo "2. Click 'Register'"
echo "3. Create an account (use any email)"
echo "4. Check your email for verification"
echo "5. Log in with your credentials"
echo ""

echo "🎉 You're all set! The app is now fully functional."
echo ""
echo "📚 Features Available:"
echo "- User authentication (register/login)"
echo "- Profile management (edit personal info, skills, portfolio)"
echo "- Job posting (for business users)"
echo "- Job browsing (for student users)"
echo "- Notifications"
echo "- Dark mode"
echo "- Real-time updates"
echo ""
echo "❌ Features NOT included (as requested):"
echo "- Google/Facebook login"
echo "- Payment system"
echo ""
